// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxYIlCFsjEJAyLkuzNVkEgEGAM4eCF12c',
    appId: '1:962141113666:web:3044e941a7be80dbe58cdb',
    messagingSenderId: '962141113666',
    projectId: 'test-project-42ee0',
    authDomain: 'test-project-42ee0.firebaseapp.com',
    storageBucket: 'test-project-42ee0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8p4yVThoNEdPFCsY8bRFEC9G-3V_QZI',
    appId: '1:962141113666:android:d1c545f345577aaae58cdb',
    messagingSenderId: '962141113666',
    projectId: 'test-project-42ee0',
    storageBucket: 'test-project-42ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0z3svTb1OAwkzMJ0WaGlA1MmFCYz4JJ0',
    appId: '1:962141113666:ios:40786894775db52ce58cdb',
    messagingSenderId: '962141113666',
    projectId: 'test-project-42ee0',
    storageBucket: 'test-project-42ee0.appspot.com',
    iosClientId: '962141113666-ghtbtk4mbhjf2gcnquadpso701b5841l.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );
}
